"""
HTM/htm_generate_configs.py
Generate random HTM-Combined hyperparameter configs and a SLURM script.

Usage (from ):
  python HTM/htm_generate_configs.py [--n-configs 128] [--seed 0]

Outputs:
  HTM/configs/config_NNNN.json …
  slurm/train_htm_array.sh
"""

import argparse
import glob
import json
import os
import random
from pathlib import Path

# Search space for hyperparameters
PARAM_SPACE = {
    "sp_columnDimensions":     [2048],
    "sp_numActiveColumns":     [25, 30, 35, 40],
    "sp_potentialPct":         [0.65, 0.80],
    "sp_synPermActiveInc":     [0.02, 0.05],
    "sp_synPermConnected":     [0.10, 0.20],
    "sp_synPermInactiveDec":   [0.003, 0.005, 0.010],
    "tm_cellsPerColumn":       [16, 32],
    "tm_activationThreshold":  [10, 13],
    "tm_initialPermanence":    [0.21, 0.31, 0.40],
    "tm_connectedPermanence":  [0.30, 0.50],
    "tm_minThreshold":         [8, 10],
    "tm_maxNewSynapseCount":   [20, 25, 30],
    "tm_permanenceIncrement":  [0.05, 0.10],
    "tm_permanenceDecrement":  [0.05, 0.10],
    "dwell_stats_enc_bits":    [16, 24, 32],
    "dwell_stats_enc_w":       [5, 7, 9],
    "flight_stats_enc_bits":   [16, 24, 32],
    "flight_stats_enc_w":      [5, 7, 9],
    "dist_stats_enc_bits":     [16, 24, 32],
    "dist_stats_enc_w":        [5, 7, 9],
    "dwell_scalar_enc_bits":   [8, 16],
    "dwell_scalar_enc_w":      [3, 5, 7],
    "flight_scalar_enc_bits":  [8, 16],
    "flight_scalar_enc_w":     [3, 5, 7],
    "dist_scalar_enc_bits":    [8, 16],
    "dist_scalar_enc_w":       [3, 5, 7],
    "warmup_steps":            [0, 2, 3],
    "al_period":               [5, 10, 15],
}

def is_valid(cfg: dict) -> bool:
    # Basic validity checks for hyperparameters
    if cfg["tm_minThreshold"] > cfg["tm_activationThreshold"]:
        return False
    if cfg["tm_activationThreshold"] > cfg["tm_maxNewSynapseCount"]:
        return False
    for w_key, bits_key in [
        ("dwell_stats_enc_w", "dwell_stats_enc_bits"),
        ("flight_stats_enc_w", "flight_stats_enc_bits"),
        ("dist_stats_enc_w", "dist_stats_enc_bits"),
        ("dwell_scalar_enc_w", "dwell_scalar_enc_bits"),
        ("flight_scalar_enc_w", "flight_scalar_enc_bits"),
        ("dist_scalar_enc_w", "dist_scalar_enc_bits"),
    ]:
        if cfg[w_key] >= cfg[bits_key]:
            return False
    return True

def sample_config(rng: random.Random) -> dict | None:
    for _ in range(1000):
        cfg = {k: rng.choice(v) for k, v in PARAM_SPACE.items()}
        if is_valid(cfg):
            return cfg
    return None

def find_start_idx(results_dir: str) -> int:
    max_idx = -1
    if not os.path.exists(results_dir):
        return 0
    for fpath in glob.glob(os.path.join(results_dir, "htm_model_*.json")):
        try:
            with open(fpath) as fh:
                r = json.load(fh)
            idx = r.get("config_idx", -1)
            if isinstance(idx, int) and idx > max_idx:
                max_idx = idx
        except Exception:
            pass
    return max_idx + 1

def write_slurm_script(n_configs: int, start_idx: int, out_path: str,
                       cache: str = "", tag: str = "", time_limit: str = "08:00:00"):
    array_range = f"{start_idx}-{start_idx + n_configs - 1}%20"
    tag_suffix  = f"_{tag}" if tag else ""
    job_name    = f"htm{tag_suffix}_train"
    log_base    = f"htm{tag_suffix}_train"
    extra_args  = ""
    if cache:
        extra_args += f' --cache "{cache}"'
    if tag:
        extra_args += f' --tag "{tag}"'
    script = f"""\
#!/bin/bash
# SLURM job array for HTM hyperparameter search
# Generated by HTM/htm_generate_configs.py
#
# Submit with (from repo root):
#   sbatch {out_path.split('/')[-1] if '/' in out_path else out_path}
#
#SBATCH --job-name={job_name}
#SBATCH --output=logs/{log_base}_%A_%a.out
#SBATCH --error=logs/{log_base}_%A_%a.err
#SBATCH --array={array_range}
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time={time_limit}

ENV_NAME=badusb
export PATH="$HOME/miniconda3/envs/$ENV_NAME/bin:$HOME/anaconda3/envs/$ENV_NAME/bin:$HOME/miniconda3/bin:$HOME/anaconda3/bin:$PATH"
source "$HOME/miniconda3/etc/profile.d/conda.sh" 2>/dev/null || source "$HOME/anaconda3/etc/profile.d/conda.sh" 2>/dev/null || true
conda activate $ENV_NAME 2>/dev/null || true
export LD_LIBRARY_PATH="$HOME/miniconda3/envs/$ENV_NAME/lib:${{CONDA_PREFIX:+$CONDA_PREFIX/lib:}}$LD_LIBRARY_PATH"

cd "$SLURM_SUBMIT_DIR"

mapfile -t CONFIGS < <(ls HTM/configs/config_*.json | sort)
CONFIG="${{CONFIGS[$SLURM_ARRAY_TASK_ID]}}"

if [[ -z "$CONFIG" ]]; then
    echo "ERROR: No config for task $SLURM_ARRAY_TASK_ID"
    exit 1
fi

echo "Running HTM training with config: $CONFIG"
python -X utf8 -u HTM/htm_train.py --config "$CONFIG"{extra_args}
"""
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w', newline='\n') as fh:
        fh.write(script)
    print(f"SLURM script -> {out_path}")

def main():
    _here = os.path.dirname(os.path.abspath(__file__))
    _badusb_root = os.path.dirname(_here)
    
    parser = argparse.ArgumentParser(description="Generate HTM hyperparameter configs")
    parser.add_argument("--n-configs", type=int, default=128, help="Number of configs to generate")
    parser.add_argument("--seed", type=int, default=0, help="RNG seed")
    parser.add_argument("--cache", default="", help="Windows cache path to embed in SLURM script (e.g. HTM/windows_cache_fullkey.pkl)")
    parser.add_argument("--tag", default="", help="Output tag to embed in SLURM script (e.g. fullkey)")
    parser.add_argument("--time", default="08:00:00", dest="time_limit", help="SLURM time limit per job (default: 08:00:00)")
    args = parser.parse_args()

    configs_dir = os.path.join(_here, "configs")
    results_dir = os.path.join(_badusb_root, "results", "HTM", "results")
    slurm_dir = os.path.join(_badusb_root, "slurm")
    logs_dir = os.path.join(_badusb_root, "logs")

    os.makedirs(configs_dir, exist_ok=True)
    os.makedirs(results_dir, exist_ok=True)
    os.makedirs(slurm_dir, exist_ok=True)
    os.makedirs(logs_dir, exist_ok=True)
    
    start_idx = find_start_idx(results_dir)
    print(f"Starting config index from: {start_idx}")

    rng = random.Random(args.seed + start_idx)
    configs = []
    seen = set()

    while len(configs) < args.n_configs:
        cfg = sample_config(rng)
        if cfg is None:
            break
        cfg["seed"] = rng.randint(0, 99999)
        key = json.dumps({k: v for k, v in cfg.items() if k != "seed"}, sort_keys=True)
        if key not in seen:
            seen.add(key)
            configs.append(cfg)

    for i, cfg in enumerate(configs):
        global_idx = start_idx + i
        path = os.path.join(configs_dir, f"config_{global_idx:04d}.json")
        with open(path, 'w') as fh:
            json.dump(cfg, fh, indent=2)

    n = len(configs)
    print(f"Generated {n} new configs in {configs_dir}")

    tag_suffix = f"_{args.tag}" if args.tag else ""
    slurm_script_name = f"train_htm{tag_suffix}_array.sh"
    slurm_script_path = os.path.join(slurm_dir, slurm_script_name)
    write_slurm_script(n, start_idx, slurm_script_path,
                       cache=args.cache, tag=args.tag, time_limit=args.time_limit)

if __name__ == "__main__":
    main()
