#!/bin/bash
# ============================================================
# SLURM array: MLP — parallel HP search (128 trials)
#
# Prerequisites (run once before submitting):
#   python MLP/generate_mlp_configs.py   # creates results/MLP/hp_trials/
#   Ensure MLP/train_dataset_fullkey.csv etc. exist
#     (generated by train_mlp.sh or fullkey_mlp.sh steps 0-4)
#
# Usage:
#   cd <repo-root>
#   python MLP/generate_mlp_configs.py
#   sbatch slurm/hpsearch_mlp_array.sh
#   # after all tasks finish:
#   sbatch slurm/collect_mlp.sh
# ============================================================
#SBATCH --job-name=mlp_hp
#SBATCH --output=logs/mlp_hp_%A_%a.out
#SBATCH --error=logs/mlp_hp_%A_%a.err
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --time=1:00:00
#SBATCH --gres=gpu:1
#SBATCH --exclude=galileo5,bruno5,nlp-pro6000-1
#SBATCH --array=0-127

set -e

ENV_NAME=badusb
export PATH="$HOME/miniconda3/envs/$ENV_NAME/bin:$HOME/anaconda3/envs/$ENV_NAME/bin:$HOME/miniconda3/bin:$HOME/anaconda3/bin:$PATH"
source "$HOME/miniconda3/etc/profile.d/conda.sh" 2>/dev/null || source "$HOME/anaconda3/etc/profile.d/conda.sh" 2>/dev/null || true
conda activate $ENV_NAME 2>/dev/null || true
export LD_LIBRARY_PATH="$HOME/miniconda3/envs/$ENV_NAME/lib:${CONDA_PREFIX:+$CONDA_PREFIX/lib:}$LD_LIBRARY_PATH"

CC_MAJOR=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 | cut -d. -f1)
if [ "${CC_MAJOR:-0}" -ge 12 ] && ! python -c "import torch; assert any('sm_12' in c for c in torch.cuda.get_arch_list())" 2>/dev/null; then
    echo "Blackwell GPU (sm_${CC_MAJOR}x) — installing PyTorch cu128"
    pip install torch --index-url https://download.pytorch.org/whl/cu128 -q
elif ! python -c "import torch; assert torch.cuda.is_available()" 2>/dev/null; then
    echo "No CUDA-enabled PyTorch — installing cu121"
    pip install torch --index-url https://download.pytorch.org/whl/cu121 -q
fi

WORK="$SLURM_SUBMIT_DIR"
TRIAL=$(printf '%04d' "$SLURM_ARRAY_TASK_ID")

echo "========================================"
echo "Array : $SLURM_ARRAY_JOB_ID  task=$SLURM_ARRAY_TASK_ID  trial=$TRIAL"
echo "Node  : $(hostname)"
echo "Start : $(date)"
echo "========================================"

cd "$WORK/MLP"

python -X utf8 model_training.py \
    --split-json "$WORK/data_split.json" \
    --mode full \
    --tag fullkey \
    --trial-config "$WORK/results/MLP/hp_trials/trial_${TRIAL}.json"

echo "========================================"
echo "End : $(date)"
echo "========================================"
